# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 18:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_employee_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateTimeField()),
                ('from_period', models.DateTimeField()),
                ('to_period', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Given',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size_a', models.SmallIntegerField()),
                ('size_b', models.SmallIntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 6, 15, 18, 51, 20, 133376))),
            ],
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size_a', models.SmallIntegerField()),
                ('size_b', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField()),
                ('from_period', models.DateTimeField()),
                ('to_period', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Taken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size_a', models.SmallIntegerField()),
                ('size_b', models.SmallIntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('paid_by_provider', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 6, 15, 18, 51, 20, 133376))),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_number',
            field=models.BigIntegerField(default=9892353227),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='taken',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Employee'),
        ),
        migrations.AddField(
            model_name='pending',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Employee'),
        ),
        migrations.AddField(
            model_name='given',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Employee'),
        ),
        migrations.AddField(
            model_name='employeepayment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Employee'),
        ),
        migrations.AddField(
            model_name='employeeadvance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Employee'),
        ),
    ]
