# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 19:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20170615_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='given',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 19, 1, 49, 5724)),
        ),
        migrations.AlterField(
            model_name='taken',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 19, 1, 49, 5724)),
        ),
    ]
