# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20170615_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivenToEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size_a', models.SmallIntegerField()),
                ('size_b', models.SmallIntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 6, 15, 19, 33, 56, 648883))),
            ],
        ),
        migrations.CreateModel(
            name='GivenToProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size_a', models.SmallIntegerField()),
                ('size_b', models.SmallIntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 6, 15, 19, 33, 56, 664538))),
            ],
        ),
        migrations.CreateModel(
            name='PendingToProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size_a', models.SmallIntegerField()),
                ('size_b', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile_number', models.BigIntegerField(unique=True)),
                ('Trading_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderAdvance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='TakeFromProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size_a', models.SmallIntegerField()),
                ('size_b', models.SmallIntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 6, 15, 19, 33, 56, 664538))),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='TakenFromEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size_a', models.SmallIntegerField()),
                ('size_b', models.SmallIntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('paid_by_provider', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 6, 15, 19, 33, 56, 664538))),
            ],
        ),
        migrations.RenameModel(
            old_name='Pending',
            new_name='PendingFromEmployee',
        ),
        migrations.RemoveField(
            model_name='given',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='taken',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='create_date',
        ),
        migrations.AlterField(
            model_name='providerpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.DeleteModel(
            name='Given',
        ),
        migrations.DeleteModel(
            name='Taken',
        ),
        migrations.AddField(
            model_name='takenfromemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Employee'),
        ),
        migrations.AddField(
            model_name='pendingtoprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
        migrations.AddField(
            model_name='giventoprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
        ),
        migrations.AddField(
            model_name='giventoemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Employee'),
        ),
        migrations.AddField(
            model_name='providerpayment',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.Provider'),
            preserve_default=False,
        ),
    ]
